site_name: Numan Documenation
site_url: https://docs.numan.ai/
site_description: Numan Documenation
site_author: Numan Team

repo_url: https://github.com/numan-ai/docs/
edit_uri: blob/main/docs/

theme:
  name: gitbook
  user_color_mode_toggle: true
  locale: en
  highlightjs: true
  hljs_languages:
    - python
    - markdown
    - json

nav:
  - Home: index.md
  - Knowledge Base: 
    - About: kb/index.md
  - Literature:
    - Literature: literature/index.md
    - Yago 4.5: literature/yago45.md


extra_css:
  - css/extra.css

exclude_docs: |
  *.py
